package org.quizapi.connections;

import com.google.gson.FieldNamingPolicy;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonSyntaxException;

import org.quizapi.exceptions.ProxyBlockException;
import org.quizapi.models.beans.OmdbTitle;
import org.quizapi.models.beans.Title;
import org.quizapi.tools.GameManager;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class OmdbConnection {
    private final String apiKey = System.getenv("API_KEY");
    private String url= "https://www.omdbapi.com/?apikey="+apiKey;
    private String json;
    private Title titulo;
    private final List<String> fakeJson = new ArrayList<>();
    //private Cache cache = new Cache();

    public void fillFakeJson(){
        fakeJson.add("{\"Title\":\"Venus Boy\",\"Year\":\"2001\",\"Rated\":\"N/A\",\"Released\":\"17 Nov 2001\",\"Runtime\":\"10 min\",\"Genre\":\"Short\",\"Director\":\"Arturo Castelán\",\"Writer\":\"N/A\",\"Actors\":\"N/A\",\"Plot\":\"One latino wistfully looks back at a pivotal sexual encounter.\",\"Language\":\"Spanish\",\"Country\":\"Mexico\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0409434\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"May\",\"Year\":\"1976\",\"Rated\":\"N/A\",\"Released\":\"N/A\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"N/A\",\"Genre\":\"Action, Comedy, Crime, Drama\",\"Director\":\"Tom Clegg\",\"Writer\":\"Trevor Preston\",\"Actors\":\"John Thaw, Dennis Waterman, Marjorie Yates, Karl Howman\",\"Plot\":\"Young Davey Holmes is arrested after an elderly money-lender whom he has visited is attacked and robbed...\",\"Language\":\"N/A\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzM5Mzc4NjU3MV5BMl5BanBnXkFtZTcwMzk3MjIzOA@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.9/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.9\",\"imdbVotes\":\"18\",\"imdbID\":\"tt0714446\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Drottningens juvelsmycke\",\"Year\":\"1967\",\"Rated\":\"N/A\",\"Released\":\"16 Mar 1967\",\"Runtime\":\"N/A\",\"Genre\":\"Drama\",\"Director\":\"N/A\",\"Writer\":\"N/A\",\"Actors\":\"Per Oscarsson, Mimmo Wåhlander, Marianne Wesén\",\"Plot\":\"N/A\",\"Language\":\"Swedish\",\"Country\":\"Sweden\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNjZlZWViZjgtNmMwZi00YmY0LThjZWEtMDQ1OTkxYjkyZDU3XkEyXkFqcGdeQXVyOTYzNDIwMDc@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"11\",\"imdbID\":\"tt0207244\",\"Type\":\"series\",\"totalSeasons\":\"1\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"AWE Overload\",\"Year\":\"2006–\",\"Rated\":\"N/A\",\"Released\":\"02 Jan 2006\",\"Runtime\":\"24 min\",\"Genre\":\"Sport\",\"Director\":\"N/A\",\"Writer\":\"N/A\",\"Actors\":\"Marcus Bagwell, Kevin Chevy, Jon Cutler\",\"Plot\":\"AWE Overload was a TV show from Action Wrestling Entertainment that aired on The Fight Network in January of 2006, there were only 7 episodes aired. All of the episodes were taped at the Investors Group Athletic Centre in Winnipeg...\",\"Language\":\"English\",\"Country\":\"Canada\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZmRlYzRiNzUtYzU5OC00NjE5LTk2MDgtYjc1NzQ0YzEzNjkyXkEyXkFqcGdeQXVyMDMwNzkyMA@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"4.2/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"4.2\",\"imdbVotes\":\"11\",\"imdbID\":\"tt0959543\",\"Type\":\"series\",\"totalSeasons\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Dummy of Danger/Sooner or Later/Jumping Jon\",\"Year\":\"1992\",\"Rated\":\"N/A\",\"Released\":\"24 Oct 1992\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"23 min\",\"Genre\":\"Animation, Comedy, Family\",\"Director\":\"Dave Brain, Allen Foster, Ron Myrick\",\"Writer\":\"Jim Davis, Mark Evanier\",\"Actors\":\"Lorenzo Music, Thom Huge, Gregg Berger\",\"Plot\":\"Dummy of Danger: Garfield discovers Jon's new ventriloquist dummy is alive. Tree Stump: Garfield asks which is smarter: a dog or a tree stump. Sooner or Later: The wolf tricks the crew into putting things off. Jumping Jon: Jon dec...\",\"Language\":\"English\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzIyZTU1NWEtYjc4MC00ZThkLTkwYTQtYTFlYjViZmUzOWEyXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"26\",\"imdbID\":\"tt0585794\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Stealing Sinatra\",\"Year\":\"2003\",\"Rated\":\"R\",\"Released\":\"24 Jan 2003\",\"Runtime\":\"96 min\",\"Genre\":\"Biography, Comedy, Drama\",\"Director\":\"Ron Underwood\",\"Writer\":\"Howard Korder\",\"Actors\":\"David Arquette, William H. Macy, James Russo\",\"Plot\":\"In need of a grubstake, a young man convinces a couple of friends to help him kidnap Frank Sinatra Jr. It's a true story.\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"Nominated for 1 Primetime Emmy. 3 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMjUzM2EzN2UtNmJiOC00MmFmLThmZWYtYTA5YjA2NzBmMjE4XkEyXkFqcGdeQXVyNTE1NjY5Mg@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"5.6/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"5.6\",\"imdbVotes\":\"787\",\"imdbID\":\"tt0311863\",\"Type\":\"movie\",\"DVD\":\"06 Oct 2016\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Cactus\",\"Year\":\"2004\",\"Rated\":\"N/A\",\"Released\":\"16 Apr 2004\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"25 min\",\"Genre\":\"Family\",\"Director\":\"Adrian Holmes\",\"Writer\":\"David McRobbie\",\"Actors\":\"Sean Ohlendorf, Michael Harrison, Heli Simpson, Megan Harrington\",\"Plot\":\"N/A\",\"Language\":\"N/A\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0578865\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Lookin' at You, Kid\",\"Year\":\"2008\",\"Rated\":\"TV-MA\",\"Released\":\"03 Feb 2008\",\"Season\":\"5\",\"Episode\":\"5\",\"Runtime\":\"56 min\",\"Genre\":\"Drama, Romance\",\"Director\":\"Angela Robinson\",\"Writer\":\"Ilene Chaiken, Kathy Greenberg, Michele Abbott\",\"Actors\":\"Jennifer Beals, Leisha Hailey, Laurel Holloman\",\"Plot\":\"Jenny throws a bash to introduce her friends to the actresses playing them in her movie; Bette and Tina try to deal with a rekindled spark; Alice outs a secretly gay sports star after he utters a homophobic slur.\",\"Language\":\"English\",\"Country\":\"Canada, United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTk5MDA2NDM0OF5BMl5BanBnXkFtZTgwNzg1MDcyNzE@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"184\",\"imdbID\":\"tt0994322\",\"seriesID\":\"tt0330251\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Buitenspel\",\"Year\":\"1979\",\"Rated\":\"N/A\",\"Released\":\"N/A\",\"Runtime\":\"18 min\",\"Genre\":\"Short\",\"Director\":\"Marion Bloem\",\"Writer\":\"Marion Bloem\",\"Actors\":\"N/A\",\"Plot\":\"N/A\",\"Language\":\"N/A\",\"Country\":\"Netherlands\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0179693\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Water Rights\",\"Year\":\"1951\",\"Rated\":\"Approved\",\"Released\":\"20 Feb 1951\",\"Season\":\"1\",\"Episode\":\"26\",\"Runtime\":\"30 min\",\"Genre\":\"Western\",\"Director\":\"Albert Herman\",\"Writer\":\"O. Henry, Raymond L. Schrock\",\"Actors\":\"Duncan Renaldo, Leo Carrillo, Tanis Chandler\",\"Plot\":\"Cisco and Pancho witness some strange behavior by a coach driver near the town of Gunniston. Suddenly they are accused of attempting to rob the stage, Cisco clearly wants to clear his name, however while investigating Cisco discov...\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMjAxMTA4MjU3NV5BMl5BanBnXkFtZTgwMjczNDg0NTE@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"27\",\"imdbID\":\"tt0541934\",\"seriesID\":\"tt0042093\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Vlastelin byta\",\"Year\":\"1932\",\"Rated\":\"N/A\",\"Released\":\"N/A\",\"Runtime\":\"15 min\",\"Genre\":\"Animation, Short\",\"Director\":\"Aleksandr Ptushko\",\"Writer\":\"Aleksandr Ptushko, Nikolai Renkov\",\"Actors\":\"N. Bravin\",\"Plot\":\"N/A\",\"Language\":\"Russian\",\"Country\":\"Soviet Union\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGUzZjc4YzUtMWFmYi00MzAxLThhMTYtZTRmNzI4Y2VhY2ZmXkEyXkFqcGdeQXVyODU3NzIwNDI@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"7.1/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"7.1\",\"imdbVotes\":\"15\",\"imdbID\":\"tt0174324\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"A Special Person\",\"Year\":\"1973\",\"Rated\":\"TV-PG\",\"Released\":\"11 Jan 1973\",\"Season\":\"6\",\"Episode\":\"15\",\"Runtime\":\"60 min\",\"Genre\":\"Crime, Drama, Mystery\",\"Director\":\"Jeffrey Hayden\",\"Writer\":\"Collier Young, Frank Chase, Ramona Chase\",\"Actors\":\"Raymond Burr, Don Galloway, Don Mitchell\",\"Plot\":\"While attending a party to set up a magazine interview, Ironside witnesses the near murder of it's playboy publisher.\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZWMzNTYyZmEtNDJkNi00NjdjLWFlYWYtM2JkYWRmZmZmMjY1XkEyXkFqcGdeQXVyMTc3Mjc4NTM@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"7.5/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"7.5\",\"imdbVotes\":\"39\",\"imdbID\":\"tt0612359\",\"seriesID\":\"tt0061266\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Episode dated 21 January 2006\",\"Year\":\"2006\",\"Rated\":\"N/A\",\"Released\":\"21 Jan 2006\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"60 min\",\"Genre\":\"Music\",\"Director\":\"N/A\",\"Writer\":\"N/A\",\"Actors\":\"James Bourne, Antony Costa, Magne Furuholmen, Danny Hall\",\"Plot\":\"N/A\",\"Language\":\"N/A\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0534417\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"The 75th Annual Academy Awards\",\"Year\":\"2003\",\"Rated\":\"N/A\",\"Released\":\"23 Mar 2003\",\"Runtime\":\"210 min\",\"Genre\":\"News\",\"Director\":\"Louis J. Horvitz, Penelope Spheeris\",\"Writer\":\"Hal Kanter, Rita Cash, Buz Kohan\",\"Actors\":\"Steve Martin, Ben Affleck, John Agar\",\"Plot\":\"Award of the American academy of cinematographic arts and sciences, from 1940th known as \\\"Oscar\\\", - American film award created in 1929 and traditionally handed to the figures of cinematographic art for their contribution to creat...\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"Won 3 Primetime Emmys. 6 wins & 7 nominations total\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNTk4NWNjNjItZDM4MS00ZmYxLWE1YWQtMzE3ZTgxOGIxZjQyXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.5/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.5\",\"imdbVotes\":\"1,048\",\"imdbID\":\"tt0346468\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Bob in nesten\",\"Year\":\"2005\",\"Rated\":\"N/A\",\"Released\":\"03 Jan 2005\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"45 min\",\"Genre\":\"Action, Drama\",\"Director\":\"N/A\",\"Writer\":\"N/A\",\"Actors\":\"Leo Madder, Gert Lahousse, Kurt Vergult, Christel Van Schoonwinkel\",\"Plot\":\"N/A\",\"Language\":\"Flemish, Dutch\",\"Country\":\"Belgium\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0707213\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Fever Pitch\",\"Year\":\"1984\",\"Rated\":\"N/A\",\"Released\":\"27 Feb 1984\",\"Season\":\"1\",\"Episode\":\"19\",\"Runtime\":\"N/A\",\"Genre\":\"Comedy, Drama\",\"Director\":\"Burt Metcalfe\",\"Writer\":\"Larry Gelbart, Dennis Koenig\",\"Actors\":\"Harry Morgan, Jamie Farr, William Christopher\",\"Plot\":\"Dr. Boyer has the need of a cooling blanket for one of his patients and enlists Klinger to find one.\",\"Language\":\"English\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZGI4YjkyZTgtODdlMS00OWVjLTk3ZDYtYzI1ODgyM2QwM2MzXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"18\",\"imdbID\":\"tt0766395\",\"seriesID\":\"tt0084969\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Cruel and Unusual\",\"Year\":\"1996\",\"Rated\":\"TV-14\",\"Released\":\"14 Dec 1996\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"48 min\",\"Genre\":\"Crime, Drama, Mystery\",\"Director\":\"Ian Sander\",\"Writer\":\"Cynthia Saunders, Sibyl Gardner\",\"Actors\":\"Ally Walker, Robert Davi, Julian McMahon\",\"Plot\":\"Sam and the team investigate a series of bizarre killings whose victims were connected to the trial of a charming murderer on death row sentenced to die within days. One of her prime suspects is a love struck protester who leads a...\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMjY3MTgzNzY4OV5BMl5BanBnXkFtZTcwMDQ3OTkyMQ@@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"81\",\"imdbID\":\"tt0679658\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Jet Pilot\",\"Year\":\"1957\",\"Rated\":\"Approved\",\"Released\":\"01 Oct 1957\",\"Runtime\":\"113 min\",\"Genre\":\"Action, Drama, Romance\",\"Director\":\"Josef von Sternberg\",\"Writer\":\"Jules Furthman\",\"Actors\":\"John Wayne, Janet Leigh, Jay C. Flippen\",\"Plot\":\"Air Force Colonel Jim Shannon is tasked to escort a defecting Soviet pilot who is scheming to lure Shannon to the USSR.\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BY2NlOWY3ZjEtMTQ4YS00Njk2LTk5YjYtMTY5MDRkNTgzNTQ5XkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"5.6/10\"},{\"Source\":\"Rotten Tomatoes\",\"Value\":\"67%\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"5.6\",\"imdbVotes\":\"2,643\",\"imdbID\":\"tt0050562\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"James Coco\",\"Year\":\"1978\",\"Rated\":\"N/A\",\"Released\":\"07 Oct 1978\",\"Season\":\"3\",\"Episode\":\"12\",\"Runtime\":\"30 min\",\"Genre\":\"Comedy, Family, Music\",\"Director\":\"Philip Casson\",\"Writer\":\"Jerry Juhl, Chris Langham, Jim Henson\",\"Actors\":\"James Coco, Frank Oz, Jerry Nelson\",\"Plot\":\"Guest star John Coco tries to add \\\"razzle dazzle\\\" to The Muppet Show.\",\"Language\":\"English\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNzdmNTQ4YTAtYzIzMi00YWI4LWJkMzQtNTczZmQ2YWQ0YmM2XkEyXkFqcGdeQXVyMjMzMzc0MjM@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"7.4/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"7.4\",\"imdbVotes\":\"117\",\"imdbID\":\"tt0653177\",\"seriesID\":\"tt0074028\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Walmart Soundcheck\",\"Year\":\"2006–\",\"Rated\":\"N/A\",\"Released\":\"01 Feb 2006\",\"Runtime\":\"N/A\",\"Genre\":\"N/A\",\"Director\":\"N/A\",\"Writer\":\"N/A\",\"Actors\":\"Rascal Flatts, Miranda Lambert, Norah Jones, Mandy Moore\",\"Plot\":\"Live music performance and interview series.\",\"Language\":\"English\",\"Country\":\"USA\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.5/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.5\",\"imdbVotes\":\"15\",\"imdbID\":\"tt0815086\",\"Type\":\"series\",\"totalSeasons\":\"6\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Hodet mitt\",\"Year\":\"2004\",\"Rated\":\"N/A\",\"Released\":\"10 Jun 2004\",\"Runtime\":\"3 min\",\"Genre\":\"Short\",\"Director\":\"Knut Petter Ryan\",\"Writer\":\"Knut Petter Ryan\",\"Actors\":\"Knut Petter Ryan\",\"Plot\":\"Using stop motion photography, Knut Petter Ryan stares into the camera and, by changing his expression, facial hair, shirt, hair, hat, scarf, makeup, and more, conveys different moods, emotions, and characters. Not a word is spoken a\",\"Language\":\"None\",\"Country\":\"Norway\",\"Awards\":\"1 win\",\"Poster\":\"N/A\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.3/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.3\",\"imdbVotes\":\"20\",\"imdbID\":\"tt0466223\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Ramblin'Man\",\"Year\":\"1979–\",\"Rated\":\"N/A\",\"Released\":\"07 Feb 1981\",\"Runtime\":\"60 min\",\"Genre\":\"Adventure, Comedy, Crime\",\"Director\":\"N/A\",\"Writer\":\"N/A\",\"Actors\":\"Jerry Reed, Geoffrey Scott, Ray Stevens\",\"Plot\":\"Two down and out cowboys wind up in Nashville and are mistaken for detectives. They are hired by the sister of a missing singer. Failed pilot episode with lots of Nashville cameos. Campy comedy/mystery.\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNWY3MTJkZDQtNWQ0Ny00MmNkLTk4NDAtNDNmOWM4ZGY2YzQ1XkEyXkFqcGdeQXVyMjcyMDU4NA@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"4.9/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"4.9\",\"imdbVotes\":\"148\",\"imdbID\":\"tt0081845\",\"Type\":\"series\",\"totalSeasons\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Tomorrow, the World!\",\"Year\":\"1944\",\"Rated\":\"Approved\",\"Released\":\"29 Dec 1944\",\"Runtime\":\"86 min\",\"Genre\":\"Drama, War\",\"Director\":\"Leslie Fenton\",\"Writer\":\"James Gow, Arnaud d'Usseau, Ring Lardner Jr.\",\"Actors\":\"Fredric March, Betty Field, Agnes Moorehead\",\"Plot\":\"German boy Emil comes to live with his American uncle who tries to teach the former Hitler Youth to reject Nazism.\",\"Language\":\"English, German\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BODEwMDllZmItYzBkNi00NDU0LTk3MzMtMjA5ZGNkOGJhODk4XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.6/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.6\",\"imdbVotes\":\"719\",\"imdbID\":\"tt0037386\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Little Dutch Mill\",\"Year\":\"1934\",\"Rated\":\"Not Rated\",\"Released\":\"26 Oct 1934\",\"Runtime\":\"9 min\",\"Genre\":\"Animation, Short, Musical\",\"Director\":\"Dave Fleischer, Willard Bowsky\",\"Writer\":\"N/A\",\"Actors\":\"Mae Questel\",\"Plot\":\"A miserly mill-keeper kidnaps two Dutch children, but their pet duck runs for help like Lassie.\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDRmNjUzNzctY2Y2MC00ZTUyLTlhZjYtZTk2ZmM4ZjA0ZTRmXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.7/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.7\",\"imdbVotes\":\"155\",\"imdbID\":\"tt0025405\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Intolerance\",\"Year\":\"2000\",\"Rated\":\"N/A\",\"Released\":\"08 Aug 2007\",\"Runtime\":\"11 min\",\"Genre\":\"Animation, Comedy, Sci-Fi\",\"Director\":\"Phil Mulloy\",\"Writer\":\"N/A\",\"Actors\":\"Joel Cutrara\",\"Plot\":\"While out eradicating space debris, a strange object is discovered and brought back to Earth. The consequences are disastrous.\",\"Language\":\"English\",\"Country\":\"United Kingdom\",\"Awards\":\"1 win & 1 nomination\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BN2VkNDhiODktN2I2Zi00OTdlLWIyOGQtOTlmODYyYTdkMTJmXkEyXkFqcGdeQXVyNjU3MzUxOTM@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"7.3/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"7.3\",\"imdbVotes\":\"287\",\"imdbID\":\"tt0359483\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Banty Raids\",\"Year\":\"1963\",\"Rated\":\"Approved\",\"Released\":\"29 Jun 1963\",\"Runtime\":\"6 min\",\"Genre\":\"Animation, Family, Short\",\"Director\":\"Robert McKimson\",\"Writer\":\"Robert McKimson, Nick Bennion\",\"Actors\":\"Mel Blanc, Stan Freberg\",\"Plot\":\"A horny hipster rooster, attracted to the hens in Foghorn Leghorn's barnyard, disguises himself as a baby foundling on Foghorn's doorstep. Foghorn adopts the girl-crazy rooster as his son, giving him access to all the chickens on ...\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNGI2OTRkNmYtZDM3OC00ZmQ4LWIwYjktZDZmYmJlYjFhZWNmXkEyXkFqcGdeQXVyMTYwNDQwMzA@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.7/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.7\",\"imdbVotes\":\"332\",\"imdbID\":\"tt0056851\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Toni\",\"Year\":\"1928\",\"Rated\":\"N/A\",\"Released\":\"21 May 1928\",\"Runtime\":\"72 min\",\"Genre\":\"Thriller\",\"Director\":\"Arthur Maude\",\"Writer\":\"Douglas Furber (script), Violet E. Powell (script), Dion Titheradge (play)\",\"Actors\":\"Jack Buchanan, Dorothy Boyd, Forrester Harvey, Hayford Hobbs\",\"Plot\":\"A rich man poses as a detective's double to save a princess from jewel thieves.\",\"Language\":\"N/A\",\"Country\":\"UK\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"5.2/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"5.2\",\"imdbVotes\":\"5\",\"imdbID\":\"tt0018494\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Killers of the Sea\",\"Year\":\"1937\",\"Rated\":\"Approved\",\"Released\":\"08 May 1937\",\"Runtime\":\"49 min\",\"Genre\":\"Documentary\",\"Director\":\"Raymond Friedgen\",\"Writer\":\"Adrian Johnson, John P. Medbury, Lowell Thomas\",\"Actors\":\"Lowell Thomas, Wallace Caswell Jr., 'Evolution' Henderson\",\"Plot\":\"A film about Captain Wallace Caswell Jr. who does all in his power to protect game fish from illegal fishing and natural predators such as sharks, octopi and whales.\",\"Language\":\"English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNTk5MmZiMzQtNGE3Yi00NjNmLWJkZDYtZTJkOGUyNTlkYjgwXkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"3.8/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"3.8\",\"imdbVotes\":\"41\",\"imdbID\":\"tt0164702\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Krazhbata v ekspresa\",\"Year\":\"1931\",\"Rated\":\"N/A\",\"Released\":\"09 Sep 1931\",\"Runtime\":\"43 min\",\"Genre\":\"Short, Crime\",\"Director\":\"Vasil Bakardzhiev\",\"Writer\":\"Vasil Bakardzhiev\",\"Actors\":\"Vasil Bakardzhiev, Simeon Simeonov, Viola Yordanova\",\"Plot\":\"In a large European city the newspaper sellers are setting the latest news. \\\"A Mysterious Theft\\\" and \\\"Buddha's Statue Missing\\\" are some of the headlines. The news is also broadcast on the radio and spreads fast. A masked man enter...\",\"Language\":\"None, Bulgarian\",\"Country\":\"Bulgaria\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNjhhYTNmYzEtOTQwYS00OTNkLWFhNzctNWYzNTZhOTg5NTc4XkEyXkFqcGdeQXVyMzg1OTY0NjI@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0332185\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"The Younger Brother\",\"Year\":\"1911\",\"Rated\":\"N/A\",\"Released\":\"25 Jul 1911\",\"Runtime\":\"N/A\",\"Genre\":\"Drama, Family, Short\",\"Director\":\"Bannister Merwin\",\"Writer\":\"Bannister Merwin\",\"Actors\":\"Herbert Prior, Richard Ridgely, Charles Sutton\",\"Plot\":\"Two brothers are strongly attached to each other. The elder man has always looked after his brother. One day, he asks him to take a hand in a game of cards. He comes out the winner, but this game leads to his downfall. He cannot g...\",\"Language\":\"None, English\",\"Country\":\"United States\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMzlhMmIwNzUtYWJmNS00YzBhLWE3OTktNmYwZDRlNjAwMWMyXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0352010\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Dead of Winter\",\"Year\":\"1996\",\"Rated\":\"TV-14\",\"Released\":\"04 Jan 1996\",\"Season\":\"2\",\"Episode\":\"11\",\"Runtime\":\"46 min\",\"Genre\":\"Drama, Romance\",\"Director\":\"Whitney Ransick\",\"Writer\":\"Michael Crichton, John Wells\",\"Actors\":\"Anthony Edwards, George Clooney, Sherry Stringfield\",\"Plot\":\"Shep and Raul enter a house with about a dozen abandoned and ill-fed children and bring them to the ER.\",\"Language\":\"English\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTk3NzAzOTI5OF5BMl5BanBnXkFtZTgwNDAxODQ2MjE@._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"441\",\"imdbID\":\"tt0567955\",\"seriesID\":\"tt0108757\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"La imagen rota\",\"Year\":\"1995\",\"Rated\":\"N/A\",\"Released\":\"01 Oct 2003\",\"Runtime\":\"45 min\",\"Genre\":\"Documentary\",\"Director\":\"Sergio Giral\",\"Writer\":\"Sergio Giral (script)\",\"Actors\":\"N/A\",\"Plot\":\"A journey to the past and present of three generation of Cuban filmmakers who have exiled from Cuba Comunist regime.\",\"Language\":\"Spanish\",\"Country\":\"USA\",\"Awards\":\"N/A\",\"Poster\":\"N/A\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"6.8/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"6.8\",\"imdbVotes\":\"5\",\"imdbID\":\"tt0460469\",\"Type\":\"movie\",\"DVD\":\"N/A\",\"BoxOffice\":\"N/A\",\"Production\":\"N/A\",\"Website\":\"N/A\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Before I Die\",\"Year\":\"1958\",\"Rated\":\"N/A\",\"Released\":\"23 Jan 1958\",\"Season\":\"2\",\"Episode\":\"20\",\"Runtime\":\"90 min\",\"Genre\":\"Comedy, Crime, Drama\",\"Director\":\"Arthur Hiller\",\"Writer\":\"Berne Giler, William Sackheim, Daniel B. Ullman\",\"Actors\":\"Joe De Santis, Anthony Eisley, Jay C. Flippen\",\"Plot\":\"A surgeon becomes convinced of the innocence of a convicted murderer based on the convict mumbling while under anesthesia. He risks his reputation to save the convict from the electric chair.\",\"Language\":\"English\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTI4ODY2NzMwOF5BMl5BanBnXkFtZTYwMDk5NjI2._V1_SX300.jpg\",\"Ratings\":[],\"Metascore\":\"N/A\",\"imdbRating\":\"N/A\",\"imdbVotes\":\"N/A\",\"imdbID\":\"tt0675552\",\"seriesID\":\"tt0048893\",\"Type\":\"episode\",\"Response\":\"True\"}");
        fakeJson.add("{\"Title\":\"Episode #1.6\",\"Year\":\"2005\",\"Rated\":\"N/A\",\"Released\":\"21 Nov 2005\",\"Season\":\"N/A\",\"Episode\":\"N/A\",\"Runtime\":\"50 min\",\"Genre\":\"Drama\",\"Director\":\"Kari Skogland\",\"Writer\":\"Angus Fraser (creator), Angus Fraser\",\"Actors\":\"Maria del Mar, Gil Bellows, Paul Soles, Jane McLean\",\"Plot\":\"It's been a month since Katie's partial mastectomy and she's ready to return to the ring and claim her title as the nation's most popular host. In another ring and with rage rising, Saul ...\",\"Language\":\"N/A\",\"Country\":\"N/A\",\"Awards\":\"N/A\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYyMzQ5OTg0MF5BMl5BanBnXkFtZTcwOTYxMTIzMQ@@._V1_SX300.jpg\",\"Ratings\":[{\"Source\":\"Internet Movie Database\",\"Value\":\"8.1/10\"}],\"Metascore\":\"N/A\",\"imdbRating\":\"8.1\",\"imdbVotes\":\"11\",\"imdbID\":\"tt0925665\",\"seriesID\":\"N/A\",\"Type\":\"episode\",\"Response\":\"True\"}");
    }

    public void addJson() {
        Random r = new Random();
        json = fakeJson.get(r.nextInt(fakeJson.size()));
    }

    public void generateURL() {
        Random random = new Random();
        int ID = random.nextInt(1500000);
        url = url + "&i=tt"+String.format("%07d", ID);
    }

    public String generateURL(String a) {
        String url= "https://www.omdbapi.com/?apikey="+apiKey;
        Random random = new Random();
        int ID = random.nextInt(1500000);
        url = url + "&i=tt"+String.format("%07d", ID);
        return url;
    }

    public void HTTPCall() throws InterruptedException, ProxyBlockException{
        try {

            HttpClient client = HttpClient.newHttpClient();
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            json = response.body();
            if (json.contains("html")){
                throw new ProxyBlockException();
            }

        }catch(IOException io){
            System.out.println(io.getMessage()+ " Erro de IO in HTTP Call");
            internalDataCall();
        }
    }

    public void deserialize(){
        try {
            Gson gson = new GsonBuilder()
                    .setFieldNamingPolicy(FieldNamingPolicy.IDENTITY)
                    .setPrettyPrinting()
                    .create();
            OmdbTitle meuTituloOmdb = gson.fromJson(json, OmdbTitle.class);
            titulo = new Title(meuTituloOmdb);

        }catch(JsonSyntaxException exception){
            System.out.println("Erro de JSON");
            System.out.println(json);
        }catch(NullPointerException exception){
            System.out.println(exception.getMessage());
        }
    }

    public Title searchTitlePerId(){
        return titulo;
    }


    public OmdbConnection() throws InterruptedException{
        try{
            externalDataCall();
        }catch (ProxyBlockException p){
            internalDataCall();
        } finally{
            deserialize();
            System.out.println(json + url);
        }
    }

    public void externalDataCall() throws ProxyBlockException, InterruptedException{
        generateURL();
        try{
            HTTPCall();
            
        }catch (Exception e){
            int i;
            for (i = 0; i<5;i++){
                System.out.println("Tentativa " + i+1 + " de 5. Requisição sem sucesso");
                HTTPCall();
            }
            System.out.println("Tentativa de contato com OMDB sem sucesso. Utilizando base de dados interna");
            internalDataCall();
        }
        GameManager.setStatus("Conexão com OMDB realizada.");
    }

    public void internalDataCall(){
        fillFakeJson();
        addJson();
        GameManager.setStatus("Sem conexão. Utilizando dados locais.");
    }
}
